=== PeterSaffarian/replit-propertyrecommender/property_recommender/data_gathering/schemas/property_record.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Property Record",
  "description": "A normalized representation of a Trade Me property listing.",
  "type": "object",
  "properties": {
    "id": {
      "type": ["string", "integer"],
      "description": "Unique identifier for the listing (e.g. ListingId)."
    },
    "title": {
      "type": "string",
      "description": "The listing title."
    },
    "price": {
      "type": "number",
      "description": "The main listing price (e.g., StartPrice or BuyNowPrice)."
    },
    "bedrooms": {
      "type": "integer",
      "description": "Number of bedrooms."
    },
    "bathrooms": {
      "type": "integer",
      "description": "Number of bathrooms."
    },
    "region": {
      "type": "string",
      "description": "Name of the region (e.g. Auckland)."
    },
    "suburb": {
      "type": "string",
      "description": "Name of the suburb."
    },
    "latitude": {
      "type": "number",
      "description": "Latitude coordinate of the property."
    },
    "longitude": {
      "type": "number",
      "description": "Longitude coordinate of the property."
    },
    "url": {
      "type": "string",
      "format": "uri",
      "description": "Direct URL to the listing on Trade Me."
    },
    "picture_href": {
      "type": "string",
      "format": "uri",
      "description": "URL of the main property image."
    },
    "open_homes": {
      "type": "array",
      "description": "List of upcoming open-home events.",
      "items": {
        "type": "object",
        "properties": {
          "start": {
            "type": "string",
            "format": "date-time",
            "description": "Open-home start time (ISO 8601)."
          },
          "end": {
            "type": "string",
            "format": "date-time",
            "description": "Open-home end time (ISO 8601)."
          }
        },
        "required": ["start", "end"],
        "additionalProperties": false
      }
    },
    "attributes": {
      "type": "object",
      "description": "Additional listing attributes (e.g., parking, floor area)."
    }
  },
  "required": [
    "id",
    "title",
    "price",
    "bedrooms",
    "bathrooms",
    "suburb",
    "latitude",
    "longitude",
    "url"
  ],
  "additionalProperties": false
}

=== PeterSaffarian/replit-propertyrecommender/clean_properties.json
[
  {
    "id": 2149706177,
    "title": "MORTGAGEE SALE",
    "price": 0,
    "bedrooms": 4,
    "bathrooms": 2,
    "region": "Waikato",
    "suburb": "Kopu",
    "latitude": -37.2284126,
    "longitude": 175.5632629,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/waikato/thames-coromandel/kopu/listing/2149706177",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147717270.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149705839,
    "title": "Modern Living in Auckland Central",
    "price": 650000,
    "bedrooms": 3,
    "bathrooms": 2,
    "region": "Auckland",
    "suburb": "City Centre",
    "latitude": -36.8505859,
    "longitude": 174.7603149,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/auckland/auckland-city/city-centre/listing/2149705839",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147716650.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149705710,
    "title": "2VT8VN60UAQEMSM0MBY8",
    "price": 590000,
    "bedrooms": 3,
    "bathrooms": 2,
    "region": "Auckland",
    "suburb": "Clarks Beach",
    "latitude": -37.1378059,
    "longitude": 174.6989441,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/listing/2149705710",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147716650.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149705288,
    "title": "MORTGAGEE SALE",
    "price": 0,
    "bedrooms": 3,
    "bathrooms": 2,
    "region": "Waikato",
    "suburb": "Rototuna",
    "latitude": -37.7271729,
    "longitude": 175.2723999,
    "url": "https://trademe.co.nz/2149705288",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147716803.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149702777,
    "title": "MORTGAGEE SALE",
    "price": 0,
    "bedrooms": 4,
    "bathrooms": 2,
    "region": "Northland",
    "suburb": "Horahora",
    "latitude": -35.7364998,
    "longitude": 174.2911072,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/northland/whangarei/horahora/listing/2149702777",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147715510.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149702691,
    "title": "MORTGAGEE SALE",
    "price": 0,
    "bedrooms": 4,
    "bathrooms": 2,
    "region": "Northland",
    "suburb": "Central Whangarei",
    "latitude": -35.7364998,
    "longitude": 174.2911072,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/northland/whangarei/central-whangarei/listing/2149702691",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147715546.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149701924,
    "title": "AJQOMJUGSGZ1L36Q5JV3",
    "price": 0,
    "bedrooms": 6,
    "bathrooms": 6,
    "region": "Auckland",
    "suburb": "West Harbour",
    "latitude": -36.8196373,
    "longitude": 174.6278076,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/auckland/waitakere-city/west-harbour/listing/2149701924",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147715202.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149701534,
    "title": "00NEVNDA2JWOZ2SZ7UQC",
    "price": 0,
    "bedrooms": 6,
    "bathrooms": 6,
    "region": "Auckland",
    "suburb": "West Harbour",
    "latitude": -36.8196373,
    "longitude": 174.6278076,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/listing/2149701534",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147714129.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149701522,
    "title": "Savor City Living: Reserve Your Spot Today!",
    "price": 0,
    "bedrooms": 3,
    "bathrooms": 2,
    "region": "Auckland",
    "suburb": "City Centre",
    "latitude": -37.7919846,
    "longitude": 175.3019257,
    "url": "https://www.trademe.co.nz/property/listing/2149701522",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147714129.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149699969,
    "title": "ENQKFSXBCUWA2VZT3P6M",
    "price": 688000,
    "bedrooms": 3,
    "bathrooms": 2,
    "region": "Auckland",
    "suburb": "Te Atatu South",
    "latitude": -36.8741493,
    "longitude": 174.6521454,
    "url": "https://trademe.co.nz/property/listing/2149699969",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147712209.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149697084,
    "title": "MORTGAGEE SALE",
    "price": 0,
    "bedrooms": 3,
    "bathrooms": 2,
    "region": "Auckland",
    "suburb": "Kumeu",
    "latitude": -36.7748184,
    "longitude": 174.5582733,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/listing/2149697084",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147712126.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149696505,
    "title": "GE8J1TIC56NUW8JKCA50",
    "price": 0,
    "bedrooms": 3,
    "bathrooms": 2,
    "region": "Auckland",
    "suburb": "Kumeu",
    "latitude": -36.7748184,
    "longitude": 174.5582733,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/listing/2149696505",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147711384.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149695758,
    "title": "L00EZKOD7LH9WQ65JY09",
    "price": 0,
    "bedrooms": 4,
    "bathrooms": 2,
    "region": "Waikato",
    "suburb": "Meremere",
    "latitude": -37.3180237,
    "longitude": 175.0715179,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/waikato/meremere/listing/2149695758",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147711384.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149694944,
    "title": "RKS006YJ0CRQOBQ9QFTW",
    "price": 0,
    "bedrooms": 4,
    "bathrooms": 2,
    "region": "Auckland",
    "suburb": "Manurewa",
    "latitude": -37.0323105,
    "longitude": 174.9011383,
    "url": "https://www.trademe.co.nz/property/listing/2149694944",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147711004.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149694886,
    "title": "MORTGAGEE SALE",
    "price": 0,
    "bedrooms": 4,
    "bathrooms": 3,
    "region": "Auckland",
    "suburb": "Weymouth",
    "latitude": -37.045063,
    "longitude": 174.8680573,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/auckland/manukau-city/weymouth/listing/2149694886",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147710867.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149694430,
    "title": "MORTGAGEE SALE",
    "price": 0,
    "bedrooms": 3,
    "bathrooms": 2,
    "region": "Auckland",
    "suburb": "Kumeu",
    "latitude": -36.7748184,
    "longitude": 174.5582733,
    "url": "https://www.trademe.co.nz/property/residential-for-sale/listing-2149694430.htm",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147709674.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149693893,
    "title": "!!! DEVELOPERS DISCOUNT - LIMITED TIME ONLY !!!",
    "price": 0,
    "bedrooms": 3,
    "bathrooms": 3,
    "region": "Auckland",
    "suburb": "Pukekohe",
    "latitude": -37.193203,
    "longitude": 174.9272766,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/listing/2149693893",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147709689.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149693793,
    "title": "MORTGAGEE SALE",
    "price": 0,
    "bedrooms": 4,
    "bathrooms": 2,
    "region": "Auckland",
    "suburb": "Manurewa",
    "latitude": -37.0323105,
    "longitude": 174.9011383,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/auckland/manukau-city/manurewa/listing/2149693793",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147709689.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149693304,
    "title": "!!! DEVELOPERS DISCOUNT - LIMITED TIME ONLY !!!",
    "price": 0,
    "bedrooms": 3,
    "bathrooms": 3,
    "region": "Auckland",
    "suburb": "Pukekohe",
    "latitude": -37.1937943,
    "longitude": 174.9276123,
    "url": "https://www.trademe.co.nz/property/listing/2149693304",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147709689.jpg",
    "open_homes": [],
    "attributes": {}
  },
  {
    "id": 2149693044,
    "title": "MORTGAGEE SALE",
    "price": 0,
    "bedrooms": 4,
    "bathrooms": 3,
    "region": "Auckland",
    "suburb": "Weymouth",
    "latitude": -37.045063,
    "longitude": 174.8680573,
    "url": "https://www.trademe.co.nz/a/property/residential/sale/listing/2149693044",
    "picture_href": "https://trademe.sandbox.tmcdn.co.nz/photoserver/thumb/2147709689.jpg",
    "open_homes": [],
    "attributes": {}
  }
]
